export const TYPES = {
    IDatabaseService: Symbol.for("IDatabaseService"),
    IDepartmentService: Symbol.for("IDepartmentService"),
    IDepartmentRepository: Symbol.for("IDepartmentRepository"),
    IQuestionService: Symbol.for("IQuestionService"),
    IQuestionRepository: Symbol.for("IQuestionRepository"),
    IOpenAIService: Symbol.for("IOpenAIService"),
    IOpenAIRepository: Symbol.for("IOpenAIRepository"),
    IUserService: Symbol.for("IUserService"),
    IUserRepository: Symbol.for("IUserRepository"),
    IVerbalQuestionRepository: Symbol.for("IVerbalQuestionRepository"),
    IVerbalQuestionService: Symbol.for("IVerbalQuestionService"),
    IS3Service: Symbol.for("IS3Service"),
    ILangChainRepository: Symbol.for("ILangChainRepository"),
    ILangChainService: Symbol.for("ILangChainService"),
}